### PR TITLE
changes cursor pointer

### PR DESCRIPTION
**Pull request by Ashish020202**
changes cursor pointer

### CODE REVIEW

**Comment by yashsarnaik22** [comment]
@Ashish020202 do some bigger change.
you can create a section for pricing, or create a section to show cars and rides available.
I can't merge this one small change.

**Comment by Ashish020202** [comment]
Sure, Yash
I will add pricing section.

**Review by yashsarnaik22 — CHANGES_REQUESTED** [review]
@Ashish020202 Good work, but can you please make a change like some simple spelling errors.
like adress --> address 
also try to add comments in the Css and Js files what is about. 
Good luck!

**Comment by yashsarnaik22** [comment]
@Ashish020202 also please try to resolve the conflict.

**Pull request closed without merging**
